apiVersion: v1
kind: Pod
metadata:
  name: k8s-infrastructure-failure-test
  namespace: demo
  labels:
    test-scenario: "true"
spec:
  restartPolicy: Never
  containers:
  - name: web-frontend
    image: ghcr.io/podmortem/podmortem/test-logs:latest
    imagePullPolicy: Always
    command: ["/scripts/log-runner.sh"]
    args: ["k8s-infrastructure-failure"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "25m"