apiVersion: v1
kind: Pod
metadata:
  name: microservices-cascade-failure-test
  namespace: demo
  labels:
    test-scenario: "true"
spec:
  restartPolicy: Never
  containers:
  - name: order-service
    image: ghcr.io/podmortem/test-logs:latest
    imagePullPolicy: Always
    command: ["/scripts/log-runner.sh"]
    args: ["microservices-cascade-failure"]
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"