apiVersion: v1
kind: Pod
metadata:
  name: quarkus-complex-failure-test
  namespace: demo
  labels:
    test-scenario: "true"
spec:
  restartPolicy: Never
  containers:
  - name: quarkus-app
    image: ghcr.io/podmortem/podmortem/test-logs:latest
    imagePullPolicy: Always
    command: ["/scripts/log-runner.sh"]
    args: ["quarkus-complex-failure"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"