apiVersion: podmortem.redhat.com/v1alpha1
kind: PatternLibrary
metadata:
  name: quarkus-patterns
  namespace: podmortem-system
  labels:
    app.kubernetes.io/name: podmortem-patterns
  annotations:
    podmortem.redhat.com/description: "Quarkus patterns"
spec:
  repositories:
    - name: "quarkus-patterns"
      url: "https://github.com/podmortem/patterns-quarkus.git"
      branch: "main"
  refreshInterval: "10m"
  enabledLibraries:
    - "quarkus-core-patterns"
    - "quarkus-lifecycle-patterns"
    - "quarkus-microprofile-fault-tolerance-patterns"
    - "quarkus-data-extensions"
    - "quarkus-messaging-extensions" 
    - "quarkus-rest-extensions"
    - "quarkus-other-extensions"
    - "quarkus-security-patterns"
    - "quarkus-cloud-native-patterns" 
