---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-ai-interface-service
  namespace: podmortem-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmortem-ai-interface-service
  template:
    metadata:
      labels:
        app: podmortem-ai-interface-service
    spec:
      containers:
      - name: ai-interface
        image: ghcr.io/podmortem/podmortem-ai-interface:latest
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_LOG_LEVEL
          value: "INFO"
        # Enable external prompts if ConfigMap is mounted
        - name: PODMORTEM_PROMPTS_EXTERNAL_ENABLED
          value: "false"  # Set to "true" to enable external prompts
        - name: PODMORTEM_PROMPTS_EXTERNAL_PATH
          value: "/etc/podmortem/prompts"
        volumeMounts:
        - name: external-prompts
          mountPath: /etc/podmortem/prompts
          readOnly: true
      volumes:
      - name: external-prompts
        configMap:
          name: podmortem-external-prompts
          optional: true  # Don't fail if ConfigMap doesn't exist
