---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmortem-operator
rules:
# Core resources
- apiGroups: [""]
  resources: ["pods", "events", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

# Events API group (v1)
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# Custom Resource Definitions - needed for operator startup
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

# Podmortem custom resources
- apiGroups: ["podmortem.redhat.com"]
  resources: ["podmortems", "aiproviders", "patternlibraries"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["podmortem.redhat.com"]
  resources: ["podmortems/status", "aiproviders/status", "patternlibraries/status"]
  verbs: ["get", "update", "patch"]

# Apps resources for deployment management
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

# Event creation for operator events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podmortem-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podmortem-operator
subjects:
- kind: ServiceAccount
  name: podmortem-operator
  namespace: podmortem-system