name: Build and Push Test Pod Images

on:
  push:
    branches: [main, develop]
    paths:
      - 'local-demo/test-pods/**'
  pull_request:
    branches: [main]
    paths:
      - 'local-demo/test-pods/**'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild regardless of changes'
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: podmortem/test-logs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: ./local-demo/test-pods
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Update deployment files
      if: github.ref == 'refs/heads/main'
      run: |
        # Update image references in YAML files to use the new SHA tag
        IMAGE_TAG="${{ github.sha }}"
        FULL_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${IMAGE_TAG:0:7}"
        
        # Update all test pod YAML files
        find local-demo/test-pods -name "*.yaml" -type f -exec sed -i "s|image: ghcr.io/podmortem/podmortem/test-logs:latest|image: $FULL_IMAGE|g" {} \;
        
        echo "Updated test pod images to: $FULL_IMAGE"

    - name: Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Digest**: ${{ steps.push.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY 